config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    resources :gadgets
    resources :gadget_models
    resources :repair_costs
    resources :masters
    resources :user_gadgets
    resources :repair_bookings
    resources :repair_requests
    resources :subscriptions
    resources :user_gadget_requests
    resources :feedbacks
    resources :clients
    resources :promos
    resources :admin_identificators

    root to: "gadgets#index"
  end

  resources :repair_bookings, only: :create
  resources :repair_requests, only: :create
  resources :subscriptions, only: :create
  resources :user_gadget_requests, only: :create

  post :become_a_partner, controller: :welcome
  root 'welcome#index'
end

app/models/admin_identificator.rb
class AdminIdentificator < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/client.rb
class Client < ApplicationRecord
  enum client_type: { ppl: 0, cmp: 1 }

  mount_uploader :image, ClientUploader
end

app/models/feedback.rb
class Feedback < ApplicationRecord
  mount_uploader :image, FeedbackUploader
end

app/models/gadget.rb
class Gadget < ApplicationRecord
  has_many :gadget_models
  has_many :repair_costs, through: :gadget_models
end

app/models/gadget_model.rb
class GadgetModel < ApplicationRecord
  belongs_to :gadget
  has_many :repair_costs
end

app/models/master.rb
class Master < ApplicationRecord
  mount_uploader :image, MasterUploader
end

app/models/promo.rb
class Promo < ApplicationRecord
  mount_uploader :image, PromoUploader

  class << self
    def active
      find_by(active: true)
    end
  end
end

app/models/repair_booking.rb
class RepairBooking < ApplicationRecord
  validates :user_name, :phone, presence: true
end

app/models/repair_cost.rb
class RepairCost < ApplicationRecord
  belongs_to :gadget_model
  has_one :gadget, through: :gadget_model

  enum price_type: { price_normal: 0, price_from: 1, price_to: 2 }

  default_scope -> { order(:id) }
end

app/models/repair_request.rb
class RepairRequest < ApplicationRecord
  validates :user_name, :phone, presence: true
end

app/models/subscription.rb
class Subscription < ApplicationRecord
  validates :email, uniqueness: true, presence: true
end

app/models/user_gadget.rb
class UserGadget < ApplicationRecord
  mount_uploaders :images, UserGadgetUploader

  def image
    images.first.url
  end
end

app/models/user_gadget_request.rb
class UserGadgetRequest < ApplicationRecord
  validates :phone, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/repair_bookings_controller.rb
class RepairBookingsController < ApplicationController
  def create
    @repair_booking = RepairBooking.create(permitted_attributes)
    AdminNotificationMailer.repair_booking(@repair_booking).deliver_now if @repair_booking.valid?
  end

  private

  def permitted_attributes
    params.permit(:user_name, :phone, :description)
  end
end

app/controllers/repair_requests_controller.rb
class RepairRequestsController < ApplicationController
  def create
    @repair_request = RepairRequest.create(permitted_attributes)
    AdminNotificationMailer.repair_request(@repair_request).deliver_now if @repair_request.valid?
  end

  private

  def permitted_attributes
    params.permit(:user_name, :phone, :description)
  end
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  def create
    @subscription = Subscription.create(permitted_attributes)
  end

  private

  def permitted_attributes
    params.permit(:name, :email)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @gadgets = Gadget.all
    @masters = Master.all
    @user_gadgets = UserGadget.all
    @clients_ppl = Client.ppl
    @clients_cmp = Client.cmp
    @feedbacks = Feedback.all
    @promo = Promo.active

    @phone_numbers = ['067 598 1 333', '063 598 1 333', '066 598 1 333']
    @telegram_id = AdminIdentificator.find_by(name: 'telegram')&.value || 'ifurt'
  end

  def become_a_partner
    AdminNotificationMailer.become_a_partner(params[:name], params[:contact]).deliver_now
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def img_stars(count = 1)
    concat(*(image_tag 'star.png' * count))
  end

  def price_with_type(repair_cost)
    if repair_cost.promo_price.present? && repair_cost.promo_price >= 0
      return "От <strike>#{repair_cost.price.to_f.round(0)}</strike> #{repair_cost.promo_price.to_f.round(0)}".html_safe if repair_cost.price_from?
      return "До <strike>#{repair_cost.price.to_f.round(0)}</strike> #{repair_cost.promo_price.to_f.round(0)}".html_safe if repair_cost.price_to?
      "<strike>#{repair_cost.price.to_f.round(0)}</strike> #{repair_cost.promo_price.to_f.round(0)}".html_safe
    else
      return "От #{repair_cost.price.to_f.round(0)}" if repair_cost.price_from?
      return "До #{repair_cost.price.to_f.round(0)}" if repair_cost.price_to?
      repair_cost.price.to_f.round(0)
    end
  end
end

app/views/fields/enum_field/_form.html.erb
<div class="field-unit__label">
  <%= f.label field.attribute %>
</div>
<div class="field-unit__field">
  <%= f.select(field.attribute, field.selectable_options.collect { |e| [t(e), e]}) %>
</div>

app/views/fields/enum_field/_index.html.erb
<%= field.to_s %>

app/views/fields/enum_field/_show.html.erb
<%= t(field.to_s) %>

app/views/fields/image_field/_form.html.erb
<div class="field-unit__label">
  <%= f.label field.attribute %>
</div>
<div class="field-unit__field">
  <%= f.file_field field.attribute %>
</div>

app/views/fields/image_field/_index.html.erb
<% if field.data.present? %>
  <%= image_tag field.data.url, style: 'width: 50px;' %>
<% end %>

app/views/fields/image_field/_show.html.erb
<% if field.data.present? %>
  <%= image_tag field.data.url, style: 'width: 150px;' %>
<% end %>

app/views/fields/images_field/_form.html.erb
<div class="field-unit__label">
  <%= f.label field.attribute %>
</div>
<div class="field-unit__field">
  <%= f.file_field field.attribute, multiple: true %>
</div>

app/views/fields/images_field/_index.html.erb
<% if field.data.present? %>
  <% field.data.each do |image| %>
    <%= image_tag image.url, style: 'width: 50px;' %>
  <% end %>
<% end %>

app/views/fields/images_field/_show.html.erb
<% if field.data.present? %>
  <% field.data.each do |image| %>
    <%= image_tag image.url, style: 'width: 150px;' %>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Imolodca</title>
    <%= csrf_meta_tags %>

    <meta name="viewport" id="myviewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <meta property="og:image" content="<%= asset_url 'imolodca_logo-01-og.png' %>" />
    <title>Ай, молодца!</title>
    <link rel="shortcut icon" href="img/favicon.ico" type="image/x-icon">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% flash.each do |key, value| %>
      <script>
        new Noty({
          text: '<%= j value %>',
          type: '<%= key %>',
          layout: 'top',
          timeout: 3000
        }).show();
      </script>
    <% end %>

    <%= render 'shared/header' %>

    <%= yield %>

    <div id="blueimp-gallery" class="blueimp-gallery blueimp-gallery-controls">
      <div class="slides"></div>
      <h3 class="title"></h3>
      <a class="prev">‹</a>
      <a class="next">›</a>
      <a class="close">×</a>
      <a class="play-pause"></a>
      <ol class="indicator"></ol>
    </div>
  </body>
</html>

app/views/shared/_book_repair_modal.html.erb
<div class="modal fade" id="bookRepairModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h3 class="modal-title text-center" id="myModalLabel"><b>Забронировать ремонт</b></h3>
      </div>
      <div class="modal-body">
        <%= form_tag repair_bookings_path, remote: true do %>
          <div class="row">
            <div class="col-sm-6">
              <%= text_field_tag :user_name, nil, placeholder: 'Ваше имя', class: 'custom-input bordered margin-b-30' %>
            </div>
            <div class="col-sm-6">
              <%= text_field_tag :phone, nil, placeholder: 'Контактный телефон', class: 'custom-input bordered margin-b-30' %>
            </div>
            <div class="col-sm-12">
              <%= text_area_tag :description, nil, placeholder: 'Я хочу забронировать ремонт...', class: 'custom-input bordered margin-b-30' %>
              <div class="text-center">
                <%= submit_tag 'Отправить', class: 'btn btn-primary padding-h-50' %>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_call_master_modal.html.erb
<div class="modal fade" id="callMasterModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h3 class="modal-title text-center" id="myModalLabel"><b>Получить консультацию</b></h3>
      </div>
      <div class="modal-body">
        <%= form_tag repair_requests_path, remote: true do %>
          <div class="row">
            <div class="col-sm-6">
              <%= text_field_tag :user_name, nil, placeholder: 'Ваше имя', class: 'custom-input bordered margin-b-30' %>
            </div>
            <div class="col-sm-6">
              <%= text_field_tag :phone, nil, placeholder: 'Контактный телефон', class: 'custom-input bordered margin-b-30' %>
            </div>
            <div class="col-sm-12">
              <div class="text-center">
                <%= submit_tag 'Отправить', class: 'btn btn-primary padding-h-50' %>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_google_maps_script.html.erb
<script type="text/javascript">

  var map, infowindow, bounds, image_marker, markerCluster, drawingManager, selectedShape;
  var kyivCoords = {lat: 50.448506, lng: 30.555323}
  var markers = [];
  var contentWindows = [];

  mcOptions = {styles: [
    {
      height: 53,
      url: "https://raw.githubusercontent.com/googlemaps/v3-utility-library/master/markerclustererplus/images/m1.png",
      width: 53
    },
    {
      height: 56,
      url: "https://raw.githubusercontent.com/googlemaps/v3-utility-library/master/markerclustererplus/images/m2.png",
      width: 56
    },
    {
      height: 66,
      url: "https://raw.githubusercontent.com/googlemaps/v3-utility-library/master/markerclustererplus/images/m3.png",
      width: 66
    },
    {
      height: 78,
      url: "https://raw.githubusercontent.com/googlemaps/v3-utility-library/master/markerclustererplus/images/m4.png",
      width: 78
    },
    {
      height: 90,
      url: "https://raw.githubusercontent.com/googlemaps/v3-utility-library/master/markerclustererplus/images/m5.png",
      width: 90
    }
  ]}

  function initMap() {
    map = new google.maps.Map(document.getElementById('map'), {
      scrollwheel: false
    });
    infowindow = new google.maps.InfoWindow();
    markerCluster = new MarkerClusterer(map, null, mcOptions);
    masters = JSON.parse('<%= j @masters.to_json.html_safe %>');

    for(i = 0; i < masters.length; i++) {
      addMarker(masters[i]);
    }
    showMarkers();
  }

  function addMarker(master) {
    new google.maps.Circle({
      strokeColor: '#000000',
      strokeOpacity: 0.3,
      strokeWeight: 1,
      fillColor: master.radius_color,
      fillOpacity: 0.1,
      map: map,
      center: {lat: master.lat, lng: master.lng},
      radius: 200
    });
    if (master.marker_img && master.marker_img.length > 1) {
      var markerImg = master.marker_img
    } else {
      var markerImg = 'https://s3.eu-central-1.amazonaws.com/imolodca-dev/static/repair-marker.png';
    }
    var marker = new google.maps.Marker({
      position: {lat: parseFloat(master.lat), lng: parseFloat(master.lng)},
      icon: {
        url: markerImg,
        size: new google.maps.Size(25, 25),
      },
      animation: google.maps.Animation.DROP,
      title: master.name
    });
    marker.addListener('click', function() {
      var stars = ""
      for (i = 1; i<=master.rating; i++) { stars += '<%= image_tag 'star.png' %>' }
      content = '<div class="user-content-window">'+
        '<div class="row">'+
        '<div class="col-xs-4 text-center margin-t-40 user-img"><img src="'+master.image.url+'"></img></div>'+
        '<div class="col-xs-8"><h4><b>' + master.name + '</b></h4>' +
        '<div class="stars">'+
        stars +
        '</div>' +
        'Опыт: '+master.experience + '<br><br>' +
        'Информация: '+master.repairs_done + '<br><br>' +
        '<input type="submit" value="Выбрать мастера" data-toggle="modal" data-target="#bookRepairModal"'+
        'class="btn btn-primary btn-sm margin-t-20" style="width: 100%;" data-master="'+master.name+'('+master.id+')">'+
        '</div></div></div>'
      infowindow.setContent(content);
      infowindow.open(map, marker);
    });
    markers.push(marker);
  }

  function drop(i, markerCluster) {
    setTimeout(function(){
      markerCluster.addMarker(markers[i]);
    }, 200);
  }

  function setMapOnAll(map) {
    bounds = new google.maps.LatLngBounds();
    for (var i = 0; i < markers.length; i++) {

      if (map) {
        drop(i, markerCluster);
        bounds.extend(markers[i].position);
      } else {
        markers[i].setMap(map);
        markerCluster.clearMarkers();
      }
    }
    if (map) {
      map.setCenter(bounds.getCenter());
      if (markers.length === 1) {
        map.setZoom(15);
      } else {
        map.fitBounds(bounds);
      }
    }
  }

  function setKiyv(map) {
    map.setZoom(11);
    map.setCenter(kyivCoords);
  }

  function clearMarkers() {
    setMapOnAll(null);
  }

  function prepareWindows() {

  }

  function showMarkers() {
    if (markers.length > 0) {
      setMapOnAll(map);
    } else {
      setKiyv(map)
    }
  }

  function deleteMarkers() {
    clearMarkers();
    markers = [];
  }

</script>

<script defer
  src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAErTW2pEvDgart3OfTMeOWF9GFbMQ1dUA&libraries=drawing&callback=initMap">
</script>

app/views/shared/_header.html.erb
<header>
  <nav class="navbar navbar-fixed-top navbar-default">
    <div class="container">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to root_path, class: 'navbar-brand' do %>
          <%= image_tag 'imolodca_logo-01.png' %>
        <% end %>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <li>
            <table><tbody>
              <tr><td><%= @phone_numbers[1] %></td></tr>
              <tr>
                <td><%= @phone_numbers[0] %></td>
                <td><%= image_tag 'viber.png' %></td>
                <td><%= image_tag 'telegram.png' %></td>
                <td><%= image_tag 'whatsapp.png' %></td>
              </tr>
              <tr><td><%= @phone_numbers[2] %></td></tr>
            </tbody></table>
          </li>
        </ul>

        <ul class="nav navbar-nav navbar-right hidden-sm">
          <li><a href="#section2" data-turbolinks="false">Цены</a></li>
          <li><a href="#section6" data-turbolinks="false">Партнерство</a></li>
          <li><a href="#section3" data-turbolinks="false">Схема работы</a></li>
          <li><a href="#section7" data-turbolinks="false">Клиенты</a></li>
          <li><a href="#section9" data-turbolinks="false">О нас</a></li>
        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>
</header>

app/views/shared/_partnership_modal.html.erb
<div class="modal fade" id="partnershipModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h3 class="modal-title text-center" id="myModalLabel"><b>Партнёрство</b></h3>
      </div>
      <div class="modal-body">
        <p class="text-center">Мы — универсальная платформа открытая к равноправному<br>и взаимовыгодному партнерству.</p>

        <p class="text-justify">
          Мы предлагаем широкий спектр услуг по продвижению мастерови поиску потенциальных клиентов, ориентированных на качественный ремонт своих гаджетов в сжатые сроки для экономии времени и денег.
        </p>

        <p class="text-justify">
          С помощью нашей платформы у Вас появится возможность получения дополнительного доступа к корпоративным и VIP клиентам не прилагаяк этому особых усилий и финансовых затрат.
        </p>

        <p class="text-justify">
          Партнерство с нами позволит Вам дополнительно экономить средствана рекламу в интернете и даст возможность получить информацию о Вас потенциальным клиентам.
        </p>

        <p class="text-justify">
          Основными критериями необходимыми для партнерства с нами являются:<br>
          ● стаж работы в этой сфере не менее 3-х лет;<br>
          ● наличие специальных навыков по работе со сложными устройствами;<br>
          ● аккуратность в работе и материальная ответственность за произведенный ремонт;<br>
          ● сохранение и нераспространение конфиденциальных данных клиента;<br>
          ● коммуникабельность и умение идти на компромиссы клиенты.
        </p>

        <p class="text-justify">
          Также мы предлагаем наше партнерство субъектам хозяйственной деятельности, основной сферой деятельности которых являет продажа различных гаджетов и продажей аксессуаров к ним.
        </p>

        <p class="text-justify">
          При желание таких субъектов хоз.деятельности мы можем организовать на их территории пункт приема гаджетов на диагностику и ремонт.
        </p>

        <p class="text-justify">
          Это позволит привлечь на вашу территорию дополнительных клиентов, увеличить финансовые обороты и узнаваемость точки через целевую рекламу в интернете.
        </p>

        <p class="text-justify">
          Основными критериями для партнерства с нами являются:<br>
          наличие разрешительной документации для осуществления предпринимательской деятельности;<br>
          материальная ответственность перед клиентом за сданный в ремонт гаджетов.
        </p>

        <div class="text-center">
          <%= form_tag become_a_partner_path, remote: true do %>
            <div class="row">
              <div class="col-sm-12">
                <%= text_field_tag :name, nil, placeholder: 'Ваше имя', class: 'custom-input margin-b-10' %>
              </div>
              <div class="col-sm-12">
                <%= text_field_tag :contact, nil, placeholder: 'Email или телефон', class: 'custom-input margin-b-10' %>
              </div>
              <div class="col-sm-12">
                <input type="submit" value="Стать партнером" class="btn btn-primary padding-h-10"><br>
              </div>
            </div>
          <% end %>
          <h4>Подробности по тел.: <b><%= @phone_numbers[0] %></b></h4>
        </div>

      </div>
    </div>
  </div>
</div>

app/views/shared/_subscribe_modal.html.erb
<div class="modal fade" id="subscribeModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h3 class="modal-title text-center" id="myModalLabel"><b>Я хочу быть в курсе<br> всех акций и предложений</b></h3>
      </div>
      <div class="modal-body">
        <%= form_tag subscriptions_path, remote: true do %>
          <div class="row">
            <div class="col-sm-8">
              <div class="row">
                <div class="col-sm-12">
                  <%= text_field_tag :name, nil, placeholder: 'Ваше имя', class: 'custom-input bordered margin-b-30' %>
                </div>
                <div class="col-sm-12">
                  <%= text_field_tag :email, nil, placeholder: 'Ваш email', class: 'custom-input bordered margin-b-30' %>
                </div>
                <div class="col-sm-12">
                  <%= submit_tag 'Подписаться', class: 'btn btn-primary padding-h-50', style: 'width: 100%' %>
                </div>
              </div>
            </div>
            <div class="col-sm-4 text-center padding padding-t-30">
              <%= link_to image_tag('instagram.png', class: 'margin-b-10'), '#' %><br>
              <%= link_to image_tag('facebook-logo.png', class: 'margin-b-10'), 'https://www.facebook.com/Imolodca-ServiceHub-1418908538200871/', target: '_blank' %><br>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_telegram_btn.html.erb
<div id="telegram-btn">
  <%= link_to image_tag('telegram.png'), "https://telegram.me/#{@telegram_id}", target: :_blank %>
</div>

app/views/shared/_user_gadget_request_modal.html.erb
<div class="modal fade" id="userGadgetRequestModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h3 class="modal-title text-center" id="myModalLabel"><b>Условия для размещения гаджета<br> у нас на сайте</b></h3>
      </div>
      <div class="modal-body">
        <%= form_tag user_gadget_requests_path, remote: true do %>
          <div class="row">
            <div class="col-sm-6 text-center">
              <h4>Необходимость подтверждения легальности приобретения гаджета</h4>
            </div>
            <div class="col-sm-6 text-center">
              <h4>Необходимость подтверждения работоспособности гаджета</h4>
            </div>
            <div class="col-sm-10 col-sm-offset-1 margin-t-30">
              <%= text_field_tag :phone, nil, placeholder: 'Контактный телефон', class: 'custom-input bordered margin-b-30' %>
            </div>
            <div class="col-sm-12">
              <div class="text-center">
                <%= submit_tag 'Разместить гаджет', class: 'btn btn-primary padding-h-50 margin-b-20' %><br>
                <h4>Подробности по тел.: <b>066 123 45 67</b></h4>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>